---
volumes:
  cowrie-etc:
  cowrie-var:
  cowrie-log:

services:
  cowrie:
    restart: always
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var/lib/cowrie
      - cowrie-log:/cowrie/cowrie-git/var/log/cowrie
